ALTER TYPE "ContentType" ADD VALUE IF NOT EXISTS 'TVET_PROGRAMMES_BULK';
ALTER TYPE "ContentType" ADD VALUE IF NOT EXISTS 'PATHWAY';
DO $$ BEGIN
  CREATE TYPE "PathwayType" AS ENUM ('UNIVERSITY','TVET','LEARNERSHIP','DIRECT');
EXCEPTION WHEN duplicate_object THEN null; END $$;
