import { PERMISSIONS, PermissionType } from "./permissions.js";
import { Role } from "./enums.js";

export const USER_ROLES = Role;
export type UserRoleType = Role;

export const ROLE_PERMISSIONS: Record<UserRoleType, PermissionType[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.ADD_ADMIN,
    PERMISSIONS.MANAGE_PLATFORM,
    PERMISSIONS.MANAGE_AI_CONFIG,
    PERMISSIONS.MANAGE_FEATURE_FLAGS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_ALL_USERS,
    PERMISSIONS.INVITE_USERS,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS,
    PERMISSIONS.MANAGE_CONTENT_PIPELINE,
    PERMISSIONS.TRIGGER_AI_GENERATION,
    PERMISSIONS.MANAGE_PROMPTS,
    PERMISSIONS.ASSIGN_REVIEWS,
    PERMISSIONS.MANAGE_SOURCES,
    PERMISSIONS.REVIEW_CONTENT,
    PERMISSIONS.APPROVE_CONTENT,
    PERMISSIONS.REJECT_CONTENT,
    PERMISSIONS.VERIFY_APS_DATA,
    PERMISSIONS.VERIFY_DEADLINES,
    PERMISSIONS.VERIFY_BURSARIES,
  ],
  ADMIN: [
    PERMISSIONS.MANAGE_ALL_USERS,
    PERMISSIONS.INVITE_USERS,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS,
    PERMISSIONS.MANAGE_CONTENT_PIPELINE,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  MANAGER: [
    PERMISSIONS.INVITE_USERS,
    PERMISSIONS.MANAGE_LEARNERS,
    PERMISSIONS.VIEW_COHORT_REPORTS,
    PERMISSIONS.REQUEST_GENERATION,
  ],
  CONTENT_MANAGER: [
    PERMISSIONS.TRIGGER_AI_GENERATION,
    PERMISSIONS.MANAGE_PROMPTS,
    PERMISSIONS.ASSIGN_REVIEWS,
    PERMISSIONS.MANAGE_SOURCES,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS,
  ],
  REVIEWER: [
    PERMISSIONS.REVIEW_CONTENT,
    PERMISSIONS.APPROVE_CONTENT,
    PERMISSIONS.REJECT_CONTENT,
  ],
  DATA_VERIFIER: [
    PERMISSIONS.VERIFY_APS_DATA,
    PERMISSIONS.VERIFY_DEADLINES,
    PERMISSIONS.VERIFY_BURSARIES,
    PERMISSIONS.MANAGE_SOURCES,
  ],
  LEARNER: [
    PERMISSIONS.TAKE_ASSESSMENTS,
    PERMISSIONS.VIEW_CAREER_LIBRARY,
    PERMISSIONS.USE_GUIDANCE_CHAT,
    PERMISSIONS.VIEW_OWN_PROFILE,
  ],
};

export const hasPermission = (
  role: UserRoleType,
  permission: PermissionType,
): boolean => (ROLE_PERMISSIONS[role] ?? []).includes(permission);
